services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: spectrum4
      POSTGRES_USER: spectrum4
      POSTGRES_PASSWORD: spectrum4password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
      - ./migrations:/docker-entrypoint-initdb.d/migrations
    ports:
      - "5432:5432"

  backend:
    build: .
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://spectrum4:spectrum4password@db:5432/spectrum4
      SESSION_SECRET: your-session-secret
      PUBLIC_BASE_URL: http://localhost:3001
      VIRUS_SCANNING_ENABLED: "true"
      CLAMAV_HOST: "127.0.0.1"
      CLAMAV_PORT: "3310"
      # Add other env vars as needed
    ports:
      - "3001:3000"
    volumes:
      - clamav_data:/var/lib/clamav
      - quarantine_data:/app/quarantine
      - supervisor_logs:/var/log/supervisor
      - clamav_logs:/var/log/clamav
      - ./uploads:/app/uploads
    depends_on:
      - db

volumes:
  db_data:
  clamav_data:
  quarantine_data:
  supervisor_logs:
  clamav_logs: 