version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.coolify
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      APP_URL: ${APP_URL}
      CORS_ORIGIN: ${CORS_ORIGIN}
      PUBLIC_BASE_URL: ${PUBLIC_BASE_URL}
      SMTP_HOST: ${SMTP_HOST:-mail.smtp2go.com}
      SMTP_PORT: ${SMTP_PORT:-2525}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      EMAIL_FROM: ${EMAIL_FROM}
      VIRUS_SCANNING_ENABLED: ${VIRUS_SCANNING_ENABLED:-false}
      LOG_LEVEL: ${LOG_LEVEL:-WARN}
    ports:
      - "3000:3000"
    volumes:
      - app_uploads:/app/uploads
      - app_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  app_uploads:
  app_logs: 